fix: pytest.init

diff --git a/.github/workflows/python-test.yaml b/.github/workflows/python-test.yaml
--- a/.github/workflows/python-test.yaml
+++ b/.github/workflows/python-test.yaml
@@ -52,11 +52,7 @@ jobs:
         continue-on-error: true
         id: coverage
         run: |
-          coverage run -m pytest tests/ >/dev/null 2>&1
-          echo "=== Coverage Report ==="
-          if ! coverage report --fail-under=80; then
-            echo "error=Coverage is below 80%" >> $GITHUB_OUTPUT
-          fi
+          coverage report --fail-under=80 || echo "error=Coverage is below 80%" >> $GITHUB_OUTPUT
 
       - name: test results
         if: always()
